[build]
    base = "./"
    publish = "out"
    command = "yarn deploy"

[[plugins]]
    package = "@netlify/plugin-sitemap"

[build.processing]
    skip_processing = false

[build.processing.images]
    compress = true