name: gitci-next
on: [push, pull_request]
env: 
  PUBLISH_DIR: out
  PROJECT_NAME: gitci-next
  COMMIT_AUTHOR: rjoydip (Joydip Roy)
  COMMIT_EMAILID: joydipand@gmail.com
  GITHUB_USERNAME: rjoydip
  PERSONAL_GITHUB_TOKEN: ${{secrets.PERSONAL_GITHUB_TOKEN}}

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.x] 
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install && Build Packages
              run: yarn install && yarn deploy
        
            - name: GitHub Pages Deploy
              uses: appleboy/gh-pages-action@v0.0.2
              with:
                username: ${{ secrets.USERNAME }}
                password: ${{ env.PERSONAL_GITHUB_TOKEN }}
                remote_url: https://${{env.PERSONAL_GITHUB_TOKEN}}@github.com/${{env.GITHUB_USERNAME}}/${{env.PROJECT_NAME}}.git
                commit_author: ${{ env.COMMIT_AUTHOR }}
                commit_author_email: ${{ env.COMMIT_EMAILID }}
                pages_directory: ${{ env.PUBLISH_DIR }}

            - name: ZEIT Now Deployment
              uses: amondnet/now-deployment@v2.0.1
              with:
                zeit-token: ${{ env.ZEIT_TOKEN }}
                github-token: ${{ env.PERSONAL_GITHUB_TOKEN }}
                now-args: '--prod'
                now-org-id: ${{ env.ZEIT_ORG_ID}}
                now-project-id: ${{ env.ZEIT_PROJECT_ID}}
                working-directory: ./
              env:
                ZEIT_TOKEN: ${{secrets.ZEIT_TOKEN}}
                ZEIT_ORG_ID: ${{secrets.ZEIT_ORG_ID}}
                ZEIT_PROJECT_ID: ${{secrets.ZEIT_PROJECT_ID}}
                
            - name: Deploy to Netlify
              uses: netlify/actions/build@master
              env:
                GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
                # NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                NETLIFY_DIR: ${{ env.PUBLISH_DIR }}